[/]
control-center=['<Super>i']
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom8/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom9/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom10/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom11/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom12/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom13/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom14/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom15/']
home=['<Super>e']
logout=@as []
www=['<Super>1']

[custom-keybindings/custom0]
binding='<Control><Alt><Super>F10'
command='"/home/lorenzo/.local/share/myScript/Script cambio schermo/ReturnToDesktop.sh"'
name='Torna a dekstop'

[custom-keybindings/custom10]
binding='<Control><Alt><Super>F9'
command='"/home/lorenzo/.local/share/myScript/Script cambio schermo/ReturnToTV.sh"'
name='Torna alla tv'

[custom-keybindings/custom11]
binding='<Shift><Control>1'
command='"/home/lorenzo/.local/share/myScript/Script cambio output audio/BackBeatPro2.sh"'
name='Passa a cuffie Bluetooth'

[custom-keybindings/custom12]
binding='<Super>t'
command='ptyxis --new-window'
name='Apri il terminale'

[custom-keybindings/custom13]
binding='<Super>h'
command='flatpak run net.mkiol.SpeechNote --action start-listening'
name='Trascrizione Vocale'

[custom-keybindings/custom14]
binding='<Alt><Super>space'
command="/bin/bash -c 'flatpak run --command=gsettings io.github.qwersyk.Newelle set io.github.qwersyk.Newelle startup-mode \"mini\" && flatpak run io.github.qwersyk.Newelle'"
name='Avvia Assistente AI'

[custom-keybindings/custom15]
binding='<Control><Alt><Super>F8'
command='"/home/lorenzo/.local/share/myScript/Script cambio schermo/ReturnToTV_Delayed.sh"'
name='Torna a TV (delay 15 secondi)'

[custom-keybindings/custom2]
binding='<Shift><Control>q'
command='"/home/lorenzo/.local/share/myScript/Script cambio output audio/Cuffie.sh"'
name='Passa a cuffie'

[custom-keybindings/custom3]
binding='<Shift><Control>backslash'
command='"/home/lorenzo/.local/share/myScript/Script cambio output audio/Casse.sh"'
name='Passa a casse'

[custom-keybindings/custom4]
binding='<Shift><Control>Escape'
command='gnome-system-monitor'
name='System Monitor'

[custom-keybindings/custom5]
binding='<Control><Alt><Super>Pause'
command='systemctl suspend -i'
name='Sospendi il pc'

[custom-keybindings/custom7]
binding='<Super>space'
command='albert toggle'
name='Avvia ricerca'

[custom-keybindings/custom8]
binding='<Control><Alt><Super>F12'
command='ddcutil setvcp D6 05'
name='Spegni monitor'

[custom-keybindings/custom9]
binding='<Control><Alt><Super>F11'
command='ddcutil setvcp D6 01'
name='Accendi Monitor'
