# Configurazione Feral GameMode (hook ambilight)
# Vedi: https://github.com/FeralInteractive/gamemode
[custom]
start=/home/lorenzo/.local/share/myScript/GameMode/ambilight.sh start
end=/home/lorenzo/.local/share/myScript/GameMode/ambilight.sh end
